name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
    
      - name: Install and set Flutter version
        uses: subosito/flutter-action@master
        with:
          channel: master

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze lib test example
        
      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
        
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@master
        with: 
         token: ${{ secrets.CODECOV_TOKEN }} 
         file: coverage/lcov.info
